runtime: nodejs22

instance_class: F1

env_variables:
  API_URL: "https://saltaalertas.aesandes.com"
  RP5_URL: "https://rp5.ru"
  RASTER_URL: "https://us-central1-hydro-dashboard-283320.cloudfunctions.net"

automatic_scaling:
  max_instances: 1
